config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'
    
    get 'beers/new'

    root             'static_pages#home'
    get 'help'    => 'static_pages#help'
    get 'about'   => 'static_pages#about'
    get 'beers'   => 'beers#index'
    get '/beers/:id', to: 'beers#show', as: 'beer'
    get 'contact' => 'static_pages#contact'
    get 'signup'  => 'users#new'
    get 'blog'    => 'static_pages#blog'
    get 'newbeer' => 'beers#new'
    get    'login'   => 'sessions#new'
    post   'login'   => 'sessions#create'
    delete 'logout'  => 'sessions#destroy'
    resources :users
    resources :account_activations, only: [:edit]
     resources :password_resets,    only: [:new, :create, :edit, :update]
    resources :beers,              only: [:create, :destroy]

end

app/models/beer.rb
class Beer < ActiveRecord::Base
  belongs_to :user
    default_scope -> { order(created_at: :desc) }
    mount_uploader :picture, PictureUploader
    validates :user_id, presence: true
    validates :beername, presence: true, length: { maximum: 50 }
    validates :brewery, presence: true, length: { maximum: 50 }
    validates :beertype, presence: true, length: { maximum: 50 }
    validates :alcohol, presence: true, numericality: { less_than_or_equal_to: 15 }
    validates :description, presence: true, length: { maximum: 140 }
    
    private
    
    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
          errors.add(:picture, "Das Bild sollte nicht größer als 5MB sein.")
      end
    end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  def create
    @beer = current_user.beers.build(beer_params)

    if @beer.save
      flash[:success] = "Bier wurde hinzugefügt"
      @user = current_user
    else
      @feed_items = []
    end

    render 'static_pages/home'
  end

  def show
    @beer = Beer.find(params[:id])
  end

  def index
    @beers = Beer.paginate(page: params[:page])
    @newest = Beer.order("created_at desc").limit(12)
    @top5 = Beer.order("rating desc").limit(5)
  end

  def destroy
    @beer.destroy
    flash[:success] = "Bier wurde gelöscht"
    render 'static_pages/home'
  end

  private

  def beer_params
    params
      .require(:beer)
      .permit(
        :beername,
        :brewery,
        :beertype,
        :alcohol,
        :rating,
        :description,
        :picture
      )
  end

  def correct_user
    @beer = current_user.beers.find_by(id: params[:id])
    redirect_to root_url if @beer.nil?
  end
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_beer.html.erb
 <div class="col-sm-6 col-md-6 col-lg-4">
    <div class="thumbnail">
      <%= image_tag beer.picture.url if beer.picture? %>
      <div class="caption">
        <h3 class="beername"><%= beer.beername %></h3>
        <h4 class="beertype"><%= beer.beertype %></h4>
        <p class="alcohol"><%= beer.alcohol %> %</p>
        <p class="stars"><%= rating_for beer, "starrating", :star => 10 %></p>
        <span>
            <% if current_user?(beer.user) %>
            <%= link_to "löschen", beer, method: :delete,
                data: { confirm: "Bist du sicher?" } %>
            <% end %>
        </span>
      </div>
    </div>
  </div>

app/views/beers/_beer_md.html.erb
 <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag beer.picture.url if beer.picture? %>
      <div class="caption">
        <h3 class="beername"><%= beer.beername %></h3>
        <h4 class="beertype"><%= beer.beertype %></h4>
        <p class="alcohol"><%= beer.alcohol %> %</p>
        <p class="stars"><%= rating_for beer, "starrating", :star => 10 %></p>
        <span>
            <% if current_user?(beer.user) %>
            <%= link_to "löschen", beer, method: :delete,
                data: { confirm: "Bist du sicher?" } %>
            <% end %>
        </span>
      </div>
    </div>
  </div>

<li class="list-group-item beer-md">
                    		<table>
                        		<tr valign="top">
                        			<td class="col_hide" style="padding-right:60px">
                            			<%= image_tag beer.picture.url if beer.picture? %>
                            		</td>
                            		<td>
                            			<table>
                                			<tr>
                                				<%= link_to <%= beer.beername %>, beer_path %>
                            				</tr>
                            				<tr>
                                                <p class="beertype"><%= beer.beertype %></p>
                                			</tr>
                                			<tr>
                                                <p class="brewery"><%= beer.brewery %></p>
                                			</tr>
                                			<tr>
                                				<p class="alcohol"><%= beer.alcohol %> %</p>
                                			</tr>
                                			<tr>
                                                <p class="description"><%= beer.description %></p>
                                			</tr>
                                			<tr>
                                                <p class="date">gepostet von <%= link_to <%= beer.user %>, user_path %> am <%= beer.created_at %></p>
                                			</tr>
                               			</table>
                            		</td>
								</tr>
                                 	
                    		</table>
                		</li>

app/views/beers/_beer_sm.html.erb
<li class="list-group-item beer-sm">
                      	<h3 class="beername"><%= beer.beername %></h3>
                        <p class="beertype"><%= beer.beertype %></p>
                        <p class="brewery"><%= beer.brewery %></p>
                        <p class="alcohol"><%= beer.alcohol %> %</p>
                       </li>

app/views/beers/_beer_xl.html.erb
 <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag beer.picture.url if beer.picture? %>
      <div class="caption">
        <h3 class="beername"><%= beer.beername %></h3>
        <h4 class="beertype"><%= beer.beertype %></h4>
        <p class="alcohol"><%= beer.alcohol %> %</p>
        <p class="stars"><%= rating_for beer, "starrating", :star => 10 %></p>
        <span>
            <% if current_user?(beer.user) %>
            <%= link_to "löschen", beer, method: :delete,
                data: { confirm: "Bist du sicher?" } %>
            <% end %>
        </span>
      </div>
    </div>
  </div>

app/views/beers/index.html.erb
<% provide(:title, 'Alle Biere') %>
<div class="img-wide" id="beers"></div>
<div class="bg_1">
  <div class="container">
    <%= link_to "Neues Bier anlegen", root_path, :class=>"btn btn btn-outlined btn-block btn-outlined-red" %>
  </div>
</div>
<div class="bg_2">
  <div class="container beer-gallery">
          <h1>Die neuesten Biere</h1>
          <% @newest.each do |beer| %>
            <div class="col-md-4 col-lg-4 col-sm-6">
              <div class="card">
                <div class="row">
                  <div class="col-xs-7 col-sm-7 col-md-7 col-lg-7">
                    <div class="card-overlay-top">
                      <span class="badge-alcohol"><%= beer.alcohol %>%</span>
                    </div>
                    <div class="card-image">
                      <div class="img-width">
                        <% if beer.picture? %>
                          <%= link_to (image_tag beer.picture.url), beer if beer.picture? %>
                        <% else %>
                          <%= link_to (image_tag ('placeholder.jpg')), beer %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                <div class="card-content col-xs-5 col-sm-5 col-md-5 col-lg-5">
                  <div class="card-title">
                    <div>
                      <h3><%= beer.beername %></h3>
                      <p class="brewery"><%= beer.brewery %></p>
                    </div>
                    <div class="card-footer">
                      <p><%= beer.beertype %></p>
                      <p><i class="fa fa-star" aria-hidden="true"></i> <%= beer.rating %></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            </div>
          <% end %>
        </div>
      </div>

app/views/beers/new.html.erb
<% provide(:title, 'Neues Bier erstellen') %>
<div class="bg_1">
    <div class="container">
        <h1>Neues Bier erstellen</h1>
        <section class="beer_form">
            <div class="col-12-md">
                <%= render 'shared/beer_form' %>
            </div>
        </section>
    </div>
</div>

app/views/beers/show.html.erb
<% provide(:title, @beer.beername) %>
<section class="bg_1">
    <div class="container">
        <div class="col-lg-4 col-md-4 col-sm-4">
            <%= link_to (image_tag @beer.picture.url, class: 'img-width img-border'), @beer if @beer.picture? %>
            </div>
          <div class="caption col-lg-4 col-md-4 col-sm-4">
            <h3 class="beername"><%= @beer.beername %></h3>
            <h4 class="beertype"><%= @beer.beertype %></h4>
            <p class="alcohol"><%= @beer.alcohol %> %</p>
            <span>Farbe:</span>
              <!--
                <div class="progress">
                    <div class="progress-bar progress-bar-red" role="progressbar" aria-valuenow="" aria-valuemin="0" aria-valuemax="5">
                    </div>
                </div>
-->
              <span>
                <% if current_user?(@beer.user) %>
                <%= link_to "löschen", @beer, method: :delete,
                    data: { confirm: "Bist du sicher?" } %>
                <% end %>
            </span>
          </div>
        <div>
             <% if current_user %>
            <div class="caption col-lg-4 col-md-4 col-sm-4">
                <h4>Bier bewerten</h4>
                   
                <% end %>
                </div>
        </div>
    </div>
</section>