config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'
    
    get 'beers/new'

    root             'static_pages#home'
    get 'help'    => 'static_pages#help'
    get 'about'   => 'static_pages#about'
    get 'beers'   => 'beers#index'
    get '/beers/:id', to: 'beers#show', as: 'beer'
    get 'contact' => 'static_pages#contact'
    get 'signup'  => 'users#new'
    get 'blog'    => 'static_pages#blog'
    get 'newbeer' => 'beers#new'
    get    'login'   => 'sessions#new'
    post   'login'   => 'sessions#create'
    delete 'logout'  => 'sessions#destroy'
    resources :users
    resources :account_activations, only: [:edit]
     resources :password_resets,    only: [:new, :create, :edit, :update]
    resources :beers,              only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer>
            <div class="row">
                <div class="col-md-4">
                    <span class="copyright">Copyright &copy; Aufeinbierchen 2016</span>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                        <li><a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li><a href="#">Privacy Policy</a>
                        </li>
                        <li><a href="#">Terms of Use</a>
                        </li>
                    </ul>
                </div>
            </div>
    </footer>

app/views/layouts/_header.html.erb
<header>
            <div class="intro-text">
                <div class="intro-heading">Auf ein Bierchen</div>
                <div class="intro-lead-in"><b>Biere</b> bewerten - <b>Biere</b> suchen - <b>Biere</b> finden</div>
                <%= link_to "Jetzt anmelden", signup_path, :class=>"page-scroll btn btn-xl" %>
                <%= link_to "Einloggen", login_path, :class=>"page-scroll btn btn-xl btn-green" %>
            </div>
</header>

app/views/layouts/_nav.html.erb
            <nav class="navbar navbar-default navbar-fixed-top">
                <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="root_path"><%= link_to image_tag('Aufeinbierchen.png', class: 'pull-left'), root_path %></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <%= link_to "Biere", beers_path %>
                    </li>
                    <li>
                        <%= link_to "Mitglieder", users_path %>
                    </li>
                    <li>
                        <%= link_to "Blog", blog_path %>
                        
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Kontakt</a>
                    </li>
                    <% if logged_in? %>
                    <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Profil <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><%= link_to "Profil", current_user %></li>
                    <li><%= link_to "Einstellungen", edit_user_path(current_user) %></li>
                    <li class="divider"></li>
                    <li>
                        <%= link_to "Abmelden", logout_path, method: "delete" %>
                    </li>
                </ul>
                </li>
                    <% else %>
                    <li>
                        <%= link_to "Login", login_path %>
                    </li>
                    <% end %>
                </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container-fluid -->
        </nav>


  

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_top.html.erb
<div class="container top">
    <a class="pull-left logo"><%= link_to (image_tag ('Logo.png')), root_path %></a>
</div>


  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
      <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,400italic,700,800' rel='stylesheet' type='text/css'>
      <link href='https://fonts.googleapis.com/css?family=Bevan' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css">
      <link href='https://fonts.googleapis.com/css?family=Arvo:400,700' rel='stylesheet' type='text/css'>
      <link href='https://fonts.googleapis.com/css?family=Lato:400,700,300,900' rel='stylesheet' type='text/css'>
      <link href="stylesheets/jquery.socialist.css" rel="stylesheet" />
      <link href="stylesheets/star-rating.css" media="all" rel="stylesheet" type="text/css" />
      <link href="stylesheets/theme-krajee-fa.css" media="all" rel="stylesheet" type="text/css" />
      <script src='javascripts/jquery.socialist.js'></script>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
      <%= yield :javascript_includes %>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body id="page-top">

    <%= render 'layouts/nav' %>
      <% unless logged_in? %>
    <%= render 'layouts/header' %>
          <% else %>
        <% end %>
         <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
            
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
<script src="javascripts/star-rating.js" type="text/javascript"></script>
<script src="path/to/js/star-rating_locale_de.js"></script>
  </body>
</html>